# Generated by Django 6.0.1 on 2026-02-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0003_alter_recommendationhistory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recommendedbook',
            name='history',
        ),
        migrations.DeleteModel(
            name='FavoriteBook',
        ),
        migrations.DeleteModel(
            name='RecommendationHistory',
        ),
        migrations.DeleteModel(
            name='RecommendedBook',
        ),
    ]
