# Generated by Django 6.0.1 on 2026-01-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('era', models.CharField(blank=True, max_length=100)),
                ('complexity_level', models.IntegerField(default=3)),
                ('cover_image', models.URLField(blank=True)),
                ('moods', models.ManyToManyField(blank=True, related_name='books', to='moods.mood')),
                ('tags', models.ManyToManyField(blank=True, to='books.tag')),
            ],
        ),
    ]
