# Generated by Django 6.0.1 on 2026-02-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('moods', '0004_mood_remove_recommendationhistory_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='book',
            name='complexity_level',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='era',
        ),
        migrations.AddField(
            model_name='book',
            name='moods',
            field=models.ManyToManyField(related_name='books', to='moods.mood'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
