# Generated by Django 6.0.1 on 2026-03-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_article_ai_tags_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archivist_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
