# Generated by Django 6.0.1 on 2026-02-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='reason',
            new_name='context_provided',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='context_type',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='why_recommended',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecommendationHistory',
        ),
    ]
