# Generated by Django 6.0.1 on 2026-01-26 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_recommendationhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendationhistory',
            old_name='user_input',
            new_name='input_text',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='book',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='context_type',
        ),
        migrations.AlterField(
            model_name='recommendationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommender_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
