# Generated by Django 6.0.1 on 2026-01-30 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_rename_user_input_recommendationhistory_input_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='user_input',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='confidence_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='context_type',
            field=models.CharField(default='feel', max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendationhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
